"""add_sender_id_to_customers

Revision ID: 2ea77e65d5a4
Revises: f7d0ec0bb8f5
Create Date: 2026-02-06 22:30:57.720940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea77e65d5a4'
down_revision: Union[str, Sequence[str], None] = 'f7d0ec0bb8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('sender_id', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'sender_id')
    # ### end Alembic commands ###
